package org.getfin.modelos.enums;

public enum EstadoAnimal {
    NACIDO, EN_CRECIENTO, REPRODUCTOR, GESTANTE, LACTANTE, ENGORDE, ENFERMO,
    EN_TRATAMIENTO, RECUPERADO, DISPONIBLE, VENDIDO, FALLECIDO, INACTIVO
}
